# Generated by Django 4.2.25 on 2025-10-31 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_aat', models.DateTimeField(auto_now=True)),
                ('is_actve', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('category', models.CharField(choices=[('business_growth', 'Business Growth'), ('consulting', 'Consulting'), ('management', 'Management'), ('customer_insights', 'Customer Insights'), ('organization', 'Organization')], max_length=50)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_aat', models.DateTimeField(auto_now=True)),
                ('is_actve', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
