# Generated by Django 4.2.25 on 2025-10-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='banner_image',
            field=models.ImageField(default=2, upload_to='list_images/'),
            preserve_default=False,
        ),
    ]
