# Generated by Django 4.2.25 on 2025-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20251121_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='is_actve',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='Update_aat',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='is_actve',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='Update_aat',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Update_aat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_actve',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
