# Generated by Django 4.2.25 on 2025-11-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='list_image',
            field=models.ImageField(default='default.jpg', upload_to='list_images/'),
        ),
    ]
