# Generated by Django 4.2.25 on 2025-11-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_is_actve_categories_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='list_image',
        ),
    ]
