# Generated by Django 4.2.25 on 2025-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('plc', 'Programmable Logic Controller (PLC)'), ('vfd', 'Variable Frequency Drive (VFD)'), ('hydraulic_valves', 'Hydraulic Valves'), ('pneumatic_valves', 'Pneumatic Valves'), ('sensors', 'Sensors'), ('actuators', 'Actuators'), ('ip_positioners', 'I/P Positioners'), ('angle_transducer', 'Angle Transducer'), ('hmi', 'Human Machine Interface (HMI)'), ('encoders', 'Encoders'), ('resolvers', 'Resolvers'), ('embedded_system', 'Embedded System')], max_length=50),
        ),
    ]
