# Generated by Django 4.2.25 on 2025-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
