# Generated by Django 4.2.25 on 2025-11-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='whatsapp_number',
        ),
    ]
