# Generated by Django 4.2.25 on 2025-12-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_image',
        ),
    ]
