# Generated by Django 4.2.25 on 2025-11-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='default.jpg', upload_to='main_image/'),
        ),
    ]
