# Generated by Django 4.2.25 on 2025-11-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='main_image',
        ),
    ]
