# Generated by Django 4.2.25 on 2025-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('business_growth', 'Business Growth'), ('consulting', 'Consulting'), ('management', 'Management'), ('customer_insights', 'Customer Insights'), ('organization', 'Organization')], max_length=50),
        ),
    ]
