# Generated by Django 4.2.25 on 2025-11-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='is_actve',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Update_aat',
            new_name='updated_at',
        ),
    ]
