# Generated by Django 4.2.25 on 2025-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='banners/')),
                ('category', models.CharField(choices=[('textile', 'Textile'), ('chemicals', 'Chemicals'), ('FMCG', 'FMCG'), ('Cement', 'Cement'), ('TEST_BENCH', 'Test Bench'), ('EDUCATIONAL_TRAINERS', 'Educational Trainers'), ('INDUSTRIAL_TRAINERS', 'Industrial Trainers'), ('OTHERS', 'Others')], max_length=255)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('brochure', models.FileField(upload_to='brochures/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
