# Generated by Django 4.2.25 on 2025-12-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='our_clients/')),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Our Client',
                'verbose_name_plural': 'Our Clients',
                'ordering': ['priority'],
            },
        ),
    ]
