# Generated by Django 4.2.25 on 2025-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('textile', 'Textile'), ('chemicals', 'Chemicals'), ('FMCG', 'FMCG'), ('Cement', 'Cement'), ('TEST_BENCH', 'Test Bench'), ('EDUCATIONAL_TRAINERS', 'Educational Trainers'), ('INDUSTRIAL_TRAINERS', 'Industrial Trainers'), ('OTHERS', 'Others')], max_length=255),
        ),
    ]
