# Generated by Django 4.2.25 on 2026-01-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ourclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brochure',
            options={'ordering': ['priority'], 'verbose_name': 'Brochure', 'verbose_name_plural': 'Brochures'},
        ),
        migrations.AddField(
            model_name='brochure',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
