# Generated by Django 5.2.10 on 2026-01-09 08:02

import apps.main.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_brochure_options_brochure_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochure',
            name='brochure',
            field=models.FileField(upload_to='brochures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx']), apps.main.models.validate_file_size]),
        ),
    ]
