# Generated by Django 4.2.25 on 2026-01-21 07:01

import apps.main.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_brochure_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochure',
            name='brochure',
            field=models.FileField(upload_to='brochures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc']), apps.main.models.validate_file_size]),
        ),
    ]
